/* 사용자 정보 */
CREATE TABLE WISETM_USER_INFO (
	USER_ID VARCHAR2(10) NOT NULL
  , USER_PW VARCHAR2(500)
  , USER_NAME VARCHAR2(100)
  , USER_EMAIL VARCHAR2(500)
  , USER_AUTH VARCHAR2(10)
  , USE_YN VARCHAR2(1)
  , CRE_DT TIMESTAMP
  , CRE_USER VARCHAR2(100)
  , MOD_DT TIMESTAMP
  , MOD_USER VARCHAR2(100)
  , PRIMARY KEY (USER_ID)
);

COMMENT ON TABLE WISETM_USER_INFO IS '사용자 정보';

COMMENT ON COLUMN WISETM_USER_INFO.USER_ID IS '사용자ID';
COMMENT ON COLUMN WISETM_USER_INFO.USER_PW IS '패스워드';
COMMENT ON COLUMN WISETM_USER_INFO.USER_NAME IS '사용자명';
COMMENT ON COLUMN WISETM_USER_INFO.USER_EMAIL IS '이메일';
COMMENT ON COLUMN WISETM_USER_INFO.USER_AUTH IS '권한';
COMMENT ON COLUMN WISETM_USER_INFO.USE_YN IS '사용여부';
COMMENT ON COLUMN WISETM_USER_INFO.CRE_DT IS '등록일자';
COMMENT ON COLUMN WISETM_USER_INFO.CRE_USER IS '등록자ID';
COMMENT ON COLUMN WISETM_USER_INFO.MOD_DT IS '수정날짜';
COMMENT ON COLUMN WISETM_USER_INFO.MOD_USER IS '수정자ID';


/* 컬렉션 정보 */
CREATE TABLE WISETM_COLLECTIONS (
	COLLECTION_ID NUMBER(11) NOT NULL
  , COLLECTION_NAME VARCHAR2(50)
  , COLLECTION_TYPE VARCHAR2(20)
  , COLLECTION_JOB VARCHAR2(20)
  , COLLECTION_DESC VARCHAR2(600)
  , COLLECTION_OWNER VARCHAR(100)
  , FIELD_INFO CLOB
  , ORIGINAL_FIELD_INFO CLOB
  , DOCUMENT_FIELD CLOB
  , CRE_DT TIMESTAMP
  , CRE_USER VARCHAR2(100)
  , MOD_DT TIMESTAMP
  , MOD_USER VARCHAR2(100)
  , PRIMARY KEY (COLLECTION_ID)
);

COMMENT ON TABLE WISETM_COLLECTIONS IS '컬렉션 정보';

COMMENT ON COLUMN WISETM_COLLECTIONS.COLLECTION_ID IS '컬랙션 ID';
COMMENT ON COLUMN WISETM_COLLECTIONS.COLLECTION_NAME IS '이름';
COMMENT ON COLUMN WISETM_COLLECTIONS.COLLECTION_TYPE IS '컬렉션구분';
COMMENT ON COLUMN WISETM_COLLECTIONS.COLLECTION_JOB IS '작업구분';
COMMENT ON COLUMN WISETM_COLLECTIONS.COLLECTION_DESC IS '설명';
COMMENT ON COLUMN WISETM_COLLECTIONS.COLLECTION_OWNER IS '소유자ID';
COMMENT ON COLUMN WISETM_COLLECTIONS.FIELD_INFO IS '문서 구조';
COMMENT ON COLUMN WISETM_COLLECTIONS.ORIGINAL_FIELD_INFO IS '원본 문서 구조';
COMMENT ON COLUMN WISETM_COLLECTIONS.DOCUMENT_FIELD IS '문서 필드';
COMMENT ON COLUMN WISETM_COLLECTIONS.CRE_DT IS '등록일자';
COMMENT ON COLUMN WISETM_COLLECTIONS.CRE_USER IS '등록자ID';
COMMENT ON COLUMN WISETM_COLLECTIONS.MOD_DT IS '수정날짜';
COMMENT ON COLUMN WISETM_COLLECTIONS.MOD_USER IS '수정자ID';



/* 컬렉션 문서정보 */
CREATE TABLE WISETM_DOCUMENTS (
	DOCUMENT_ID NUMBER(11) NOT NULL
  , COLLECTION_ID NUMBER(11)
  , DOCUMENT_CONTENT CLOB CONSTRAINT DOCUMENT_CONTENT_JSON CHECK (DOCUMENT_CONTENT IS JSON)
  , PRIMARY KEY (DOCUMENT_ID, COLLECTION_ID)
);

COMMENT ON TABLE WISETM_DOCUMENTS IS '컬렉션 문서 정보';

COMMENT ON COLUMN WISETM_DOCUMENTS.DOCUMENT_ID IS '문서 ID';
COMMENT ON COLUMN WISETM_DOCUMENTS.COLLECTION_ID IS '컬렉션 ID';
COMMENT ON COLUMN WISETM_DOCUMENTS.DOCUMENT_CONTENT IS '문서 내용';


/* 파일 업로드 정보 */
CREATE TABLE WISETM_IMPORT_PROGRESS (
	IMPORT_ID NUMBER(11) NOT NULL
  , RESOURCE_TYPE VARCHAR2(20)
  , RESOURCE_ID VARCHAR2(20)
  , FILE_NAME VARCHAR2(500)
  , LAST_MODIFIED TIMESTAMP
  , FILE_SIZE LONG
  , TOTAL_COUNT NUMBER(11)
  , VALID_COUNT NUMBER(11)
  , ERROR_HANDLE VARCHAR2(10)
  , PROGRESS VARCHAR2(20)
  , LOG_TEXT CLOB
  , IMPORT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , PRIMARY KEY (IMPORT_ID)
);

COMMENT ON TABLE WISETM_IMPORT_PROGRESS IS '컬렉션 문서 정보';

COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.IMPORT_ID IS '업로드 ID';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.RESOURCE_TYPE IS '업로드 대상';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.RESOURCE_ID IS '업로드 대상 ID';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.FILE_NAME IS '파일명';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.LAST_MODIFIED IS '업로드 일자';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.TOTAL_COUNT IS '전체건수';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.VALID_COUNT IS '성공건수';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.ERROR_HANDLE IS '에러 제어방식';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.PROGRESS IS '결과';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.LOG_TEXT IS '로그';
COMMENT ON COLUMN WISETM_IMPORT_PROGRESS.IMPORT_DT IS '업로드 일시';


/* 사전 정보 */
CREATE TABLE WISETM_DICTIONARIES (
	DICTIONARY_ID NUMBER(11) not null 
  , DICTIONARY_NAME VARCHAR2(100)
  , DICTIONARY_TYPE VARCHAR2(20)				/* WHITE : 수용어, BLANK : 불용어 */
  , DICTIONARY_DESC VARCHAR2(500)
  , DICTIONARY_SHARED_YN VARCHAR2(1)
  , DICTIONARY_OWNER VARCHAR2(100)
  , CRE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , CRE_USER VARCHAR2(100)
  , MOD_DT TIMESTAMP
  , MOD_USER VARCHAR2(100)
  , PRIMARY KEY (DICTIONARY_ID)
);

COMMENT ON TABLE WISETM_DICTIONARIES IS '컬렉션 문서 정보';

COMMENT ON COLUMN WISETM_DICTIONARIES.DICTIONARY_ID IS '사전 ID';
COMMENT ON COLUMN WISETM_DICTIONARIES.DICTIONARY_NAME IS '사전 이름';
COMMENT ON COLUMN WISETM_DICTIONARIES.DICTIONARY_TYPE IS '사전 구분';
COMMENT ON COLUMN WISETM_DICTIONARIES.DICTIONARY_DESC IS '사전 설명';
COMMENT ON COLUMN WISETM_DICTIONARIES.DICTIONARY_SHARED_YN IS '사전 소유자';
COMMENT ON COLUMN WISETM_DICTIONARIES.DICTIONARY_OWNER IS '사전 내용';
COMMENT ON COLUMN WISETM_DICTIONARIES.DICTIONARY_CONTENT IS '업로드 ID';
COMMENT ON COLUMN WISETM_DICTIONARIES.CRE_DT IS '등록날짜';
COMMENT ON COLUMN WISETM_DICTIONARIES.CRE_USER IS '등록자ID';
COMMENT ON COLUMN WISETM_DICTIONARIES.MOD_DT IS '수정날짜';
COMMENT ON COLUMN WISETM_DICTIONARIES.MOD_USER IS '수정자ID';


/* 엔트리 정보 */
CREATE TABLE WISETM_ENTRIES (
	ENTRY_ID NUMBER(11) not null 
  , DICTIONARY_ID NUMBER(11)
  , ENTRY_CONTENT VARCHAR2(100)
  , PRIMARY KEY (ENTRY_ID, DICTIONARY_ID)
);

COMMENT ON TABLE WISETM_ENTRIES IS '엔트리 정보';

COMMENT ON COLUMN WISETM_ENTRIES.ENTRY_ID IS '엔트리 ID';
COMMENT ON COLUMN WISETM_ENTRIES.DICTIONARY_ID IS '사전 ID';
COMMENT ON COLUMN WISETM_ENTRIES.ENTRY_CONTENT IS '엔트리';


/* 동의어 정보 */
CREATE TABLE WISETM_SYNONYM (
	SYNONYM_ID NUMBER(11) not null 
  , ENTRY_ID NUMBER(11) 
  , DICTIONARY_ID NUMBER(11)
  , SYNONYM_CONTENT VARCHAR2(100)
  , PRIMARY KEY (SYNONYM_ID)
);

COMMENT ON TABLE WISETM_SYNONYM IS '엔트리 정보';

COMMENT ON COLUMN WISETM_SYNONYM.SYNONYM_ID IS '동의어 ID';
COMMENT ON COLUMN WISETM_SYNONYM.ENTRY_ID IS '엔트리 ID';
COMMENT ON COLUMN WISETM_SYNONYM.DICTIONARY_ID IS '사전 ID';
COMMENT ON COLUMN WISETM_SYNONYM.SYNONYM_CONTENT IS '동의어';


/* 활동이력 정보 */
CREATE TABLE WISETM_ACTION_HISTORY (
	ACTION_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , ACTION_TYPE VARCHAR2(50)
  , RESOURCE_ID NUMBER(11)
  , RESOURCE_TYPE VARCHAR2(20) 
  , ACTION_MSG VARCHAR2(500)
  , ACTION_USER VARCHAR2(100)
);

COMMENT ON TABLE WISETM_ACTION_HISTORY IS '엔트리 정보';

COMMENT ON COLUMN WISETM_ACTION_HISTORY.ACTION_DT IS '활동일시';
COMMENT ON COLUMN WISETM_ACTION_HISTORY.ACTION_TYPE IS '활동타입';
COMMENT ON COLUMN WISETM_ACTION_HISTORY.RESOURCE_ID IS '리소스 ID';
COMMENT ON COLUMN WISETM_ACTION_HISTORY.RESOURCE_TYPE IS '리소스 유형';
COMMENT ON COLUMN WISETM_ACTION_HISTORY.ACTION_MSG IS '활동내역';
COMMENT ON COLUMN WISETM_ACTION_HISTORY.ACTION_USER IS '사용자 ID';


/* 서버 정보 */
CREATE TABLE WISETM_SERVER (
	SERVER_ID NUMBER(11) NOT NULL
  , SERVER_NAME VARCHAR2(100)
  , SERVER_DESC VARCHAR2(500)
  , SERVER_TYPE VARCHAR2(10)
  , SERVER_TASK VARCHAR2(20)
  , SERVER_IP VARCHAR2(15) not null
  , SERVER_PORT NUMBER(11) not null
  , CRE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , CRE_USER VARCHAR2(100)
  , MOD_DT TIMESTAMP
  , MOD_USER VARCHAR2(100)
  , PRIMARY KEY (SERVER_ID)
);

COMMENT ON TABLE WISETM_SERVER IS '서버 정보';

COMMENT ON COLUMN WISETM_SERVER.SERVER_ID IS '서버 ID';
COMMENT ON COLUMN WISETM_SERVER.SERVER_NAME IS '서버 이름';
COMMENT ON COLUMN WISETM_SERVER.SERVER_DESC IS '설명';
COMMENT ON COLUMN WISETM_SERVER.SERVER_TYPE IS '서버 구분';	/* TEST / PROD */
COMMENT ON COLUMN WISETM_SERVER.SERVER_TYPE IS '서버 작업';
COMMENT ON COLUMN WISETM_SERVER.SERVER_IP IS 'IP 주소';
COMMENT ON COLUMN WISETM_SERVER.SERVER_PORT IS 'PORT';
COMMENT ON COLUMN WISETM_SERVER.CRE_DT IS '등록날짜';
COMMENT ON COLUMN WISETM_SERVER.CRE_USER IS '등록자 ID';
COMMENT ON COLUMN WISETM_SERVER.MOD_DT IS '수정날짜';
COMMENT ON COLUMN WISETM_SERVER.MOD_USER IS '수정자 ID';


/* 프로젝트 정보 */
CREATE TABLE WISETM_PROJECTS (
	PROJECT_ID NUMBER(11) NOT NULL
  , PROJECT_NAME VARCHAR2(50)
  , PROJECT_DESC VARCHAR2(500)
  , PROJECT_OWNER VARCHAR2(50)
  , CRE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , CRE_USER VARCHAR2(100)
  , MOD_DT TIMESTAMP
  , MOD_USER VARCHAR2(100)
  , PRIMARY KEY (PROJECT_ID)
);

COMMENT ON TABLE WISETM_PROJECTS IS '프로젝트 정보';

COMMENT ON COLUMN WISETM_PROJECTS.PROJECT_ID IS '프로젝트 ID';
COMMENT ON COLUMN WISETM_PROJECTS.PROJECT_NAME IS '프로젝트명';
COMMENT ON COLUMN WISETM_PROJECTS.PROJECT_DESC IS '프로젝트 설명';
COMMENT ON COLUMN WISETM_PROJECTS.PROJECT_OWNER IS '소유자';
COMMENT ON COLUMN WISETM_PROJECTS.COLLECTION_ID IS '컬렉션 ID';
COMMENT ON COLUMN WISETM_PROJECTS.CRE_DT IS '등록날짜';
COMMENT ON COLUMN WISETM_PROJECTS.CRE_USER IS '등록자 ID';
COMMENT ON COLUMN WISETM_PROJECTS.MOD_DT IS '수정날짜';
COMMENT ON COLUMN WISETM_PROJECTS.MOD_USER IS '수정자 ID';


/* 서비스(테스크) 정보 */
CREATE TABLE WISETM_TASK (
	TASK_ID NUMBER(11) NOT NULL
  , TASK_NAME VARCHAR2(50)
  , TASK_TYPE VARCHAR(20)
  , PROJECT_ID NUMBER(11)
  , COLLECTION_ID NUMBER(11)
  , TASK_CONFIG CLOB CONSTRAINT TASK_CONFIG_JSON CHECK (TASK_CONFIG IS JSON)
  , MODEL_NAME VARCHAR(200)
  , MODEL_FILE VARCHAR2(200)
  , ENABLED VARCHAR2(1)
  , CRE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , CRE_USER VARCHAR2(100)
  , MOD_DT TIMESTAMP
  , MOD_USER VARCHAR2(100)
  , LAST_ANALYZE_DT TIMESTAMP
  , PRIMARY KEY (TASK_ID)
);

COMMENT ON TABLE WISETM_TASK IS '프로젝트 정보';

COMMENT ON COLUMN WISETM_TASK.TASK_ID IS '테스크 ID';
COMMENT ON COLUMN WISETM_TASK.TASK_NAME IS '테스크명';
COMMENT ON COLUMN WISETM_TASK.TASK_TYPE IS '테스크구분';
COMMENT ON COLUMN WISETM_TASK.PROJECT_ID IS '프로젝트 ID';
COMMENT ON COLUMN WISETM_TASK.COLLECTION_ID IS '컬렉션 ID';
COMMENT ON COLUMN WISETM_TASK.TASK_CONFIG IS '테스크 설정정보';
COMMENT ON COLUMN WISETM_TASK.MODEL_NAME IS '모델명';
COMMENT ON COLUMN WISETM_TASK.MODEL_FILE IS '모델파일';
COMMENT ON COLUMN WISETM_TASK.ENABLED IS '사용여부';
COMMENT ON COLUMN WISETM_TASK.CRE_DT IS '등록날짜';
COMMENT ON COLUMN WISETM_TASK.CRE_USER IS '등록자 ID';
COMMENT ON COLUMN WISETM_TASK.MOD_DT IS '수정날짜';
COMMENT ON COLUMN WISETM_TASK.MOD_USER IS '수정자 ID';
COMMENT ON COLUMN WISETM_TASK.LAST_ANALYZE_DT IS '마지막 분석일시';


/* 스케쥴 정보 */
CREATE TABLE WISETM_SCHEDULE (
	SCHEDULE_ID NUMBER(11) NOT NULL
  , SCHEDULE_NAME VARCHAR2(50)
  , SCHEDULE_TYPE VARCHAR2(10)
  , START_DT VARCHAR2(8)
  , START_TIME VARCHAR2(2)
  , END_DT VARCHAR2(8)
  , END_TIME VARCHAR2(2)
  , EXECUTE_INTERVAL NUMBER(2)
  , LAST_EXECUTE_DT TIMESTAMP
  , LAST_EXECUTE_STATUS VARCHAR(20)
  , TASK_ID NUMBER(11)
  , USE_YN VARCHAR2(1)
  , CRE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , CRE_USER VARCHAR2(100)
  , MOD_DT TIMESTAMP
  , MOD_USER VARCHAR2(100)
  , PRIMARY KEY (SCHEDULE_ID)
);

COMMENT ON TABLE WISETM_SCHEDULE IS '스케쥴 정보';

COMMENT ON COLUMN WISETM_SCHEDULE.SCHEDULE_ID IS '스케쥴 ID';
COMMENT ON COLUMN WISETM_SCHEDULE.SCHEDULE_NAME IS '스케쥴명';
COMMENT ON COLUMN WISETM_SCHEDULE.SCHEDULE_TYPE IS '스케쥴 타입';
COMMENT ON COLUMN WISETM_SCHEDULE.START_DT IS '시작일자';
COMMENT ON COLUMN WISETM_SCHEDULE.START_TIME IS '시작시간';
COMMENT ON COLUMN WISETM_SCHEDULE.END_DT IS '종료일자';
COMMENT ON COLUMN WISETM_SCHEDULE.END_TIME IS '종료시간';
COMMENT ON COLUMN WISETM_SCHEDULE.EXECUTE_INTERVAL IS '실행간격';
COMMENT ON COLUMN WISETM_SCHEDULE.LAST_EXECUTE_DT IS '마지막 실행일시';
COMMENT ON COLUMN WISETM_SCHEDULE.LAST_EXECUTE_STATUS IS '마지막 실행상태';
COMMENT ON COLUMN WISETM_SCHEDULE.TASK_ID IS '테스크 ID';
COMMENT ON COLUMN WISETM_SCHEDULE.USE_YN IS '사용여부';
COMMENT ON COLUMN WISETM_SCHEDULE.CRE_DT IS '등록날짜';
COMMENT ON COLUMN WISETM_SCHEDULE.CRE_USER IS '등록자 ID';
COMMENT ON COLUMN WISETM_SCHEDULE.MOD_DT IS '수정날짜';
COMMENT ON COLUMN WISETM_SCHEDULE.MOD_USER IS '수정자 ID';


/* 분석결과 */
CREATE TABLE WISETM_ANALYZE_RESULT (
	RESULT_ID NUMBER(11) NOT NULL
  , TASK_ID NUMBER(11)
  , PROJECT_ID NUMBER(11)
  , RESULT_CONTENT CLOB CONSTRAINT RESULT_CONTENT_JSON CHECK (RESULT_CONTENT IS JSON)
  , CRE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  , PRIMARY KEY (RESULT_ID, TASK_ID, PROJECT_ID)
);

COMMENT ON TABLE WISETM_ANALYZE_RESULT IS '스케쥴 정보';

COMMENT ON COLUMN WISETM_ANALYZE_RESULT.RESULT_ID IS '결과 ID';
COMMENT ON COLUMN WISETM_ANALYZE_RESULT.TASK_ID IS '서비스 ID';
COMMENT ON COLUMN WISETM_ANALYZE_RESULT.PROJECT_ID IS '프로젝트 ID';
COMMENT ON COLUMN WISETM_ANALYZE_RESULT.RESULT_CONTENT IS '분석내용';
COMMENT ON COLUMN WISETM_ANALYZE_RESULT.CRE_DT IS '생성일자';


/* 재부팅 진행모듈 정보 */
CREATE TABLE WISETM_REBOOT_STATUS (
    SERVER_IP VARCHAR2(15)
  , SERVER_PORT VARCHAR2(11)
);

COMMENT ON TABLE WISETM_REBOOT_STATUS IS '재부팅 진행모듈 정보';

COMMENT ON COLUMN WISETM_REBOOT_STATUS.SERVER_IP IS '서버 IP';
COMMENT ON COLUMN WISETM_REBOOT_STATUS.SERVER_PORT IS '서버 Port';